name: bump pull request

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: Please Choice Bump Target
        options:
          - build
          - patch
          - minor
          - major

env:
  GIT_USER_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  GIT_USER_NAME: 'github-actions[bot]'

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: run flutter version
        run: flutter --version

      - name: run flutter pub get
        run: flutter pub get

      - name: init git config
        run: |
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL

      - name: bump up version
        run: |
          echo choice: ${{ github.event.inputs.bump }}
          flutter pub run cider bump ${{ github.event.inputs.bump }} --bump-build
          echo "BUMP_VERSION=$(flutter pub run cider version)" >> $GITHUB_ENV

      - name: commit pubspec.yaml
        run: |
          git add -u pubspec.yaml
          echo "Bumped version number to $BUMP_VERSION" | git commit --file=-

      - name: create releaser branch
        run: |
          git checkout -b releases/$BUMP_VERSION
          echo "RELEASE_BRANCH=releases/$BUMP_VERSION" >> $GITHUB_ENV

      - name: push branch
        run: |
          git push -u origin $RELEASE_BRANCH

      - name: create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create -B main -t "Release $BUMP_VERSION" -b "Release $BUMP_VERSION" --head $RELEASE_BRANCH
